---
cluster:
  core:
    prefix: core
    nodes: 2
    ncpu: 2
    mem: 1024
  kube-master:
    prefix: kube-master
    nodes: 2
    ncpu: 2
    mem: 1024
  kube-worker:
    prefix: kube-worker
    nodes: 2
    ncpu: 2
    mem: 1024

