# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure(2) do |config|
    servers=[
      {
        :hostname => "host-discovery",
        :ip => "192.168.56.2",
        :ram => 512,
        :cpu => 2
      }
    ] 

    
    servers.each do |machine|
        #config.vm.boot_timeout = 1000
        config.vm.define machine[:hostname] do |node|
            node.landrush.enabled = true
            node.vm.box = "centos/7"
            node.vm.hostname = machine[:hostname]
            node.vm.network "private_network", ip: machine[:ip], name: "vboxnet0", adapter: 2
            node.vm.provision "file", source: "dnsmasq.conf", destination: "/var/tmp/dnsmasq.conf.tmp"
            node.vm.provision "shell", path: "bootstrap.sh"
        end
    end
end
