# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure(2) do |config|
    servers=[
      {
        :hostname => "gluster01",
        :ip => "192.168.56.10",
        :ram => 2024,
        :cpu => 2
      },
      {
        :hostname => "gluster02",
        :ip => "192.168.56.11",
        :ram => 2048,
        :cpu => 2
      }
    ] 

    
    servers.each do |machine|
        #config.vm.boot_timeout = 1000
        config.vm.define machine[:hostname] do |node|
            node.vm.box = "centos/7"
            node.vm.provider "virtualbox" do |vb|
                # Get disk path
                line = `VBoxManage list systemproperties | grep "Default machine folder"`
                vb_machine_folder = line.split(':')[1].strip()
                second_disk = File.join(vb_machine_folder, "gluster", machine[:hostname], 'disk2.vdi') 
                unless File.exist?(second_disk)
                    vb.customize [ 'createhd', '--filename', second_disk, '--format',  
                        'VDI', '--size', 60 * 1024]
                end
                vb.customize ['storageattach', :id, '--storagectl', 'IDE Controller', 
                    '--port', 0, '--device', 1, '--type', 'hdd', '--medium', second_disk]

            end
            node.vm.provision "shell", path: "bootstrap.sh"
            node.vm.provision "shell" do |s|
                s.path = "gluster_init.sh"
                s.args = machine[:hostname]
            end
            node.vm.network "private_network", ip: machine[:ip], name: "vboxnet0", adapter: 2
        end
    end
end
